### ISSUE TITLE
Jonathan Kinred completes task, no time or arrival points.

### ISSUE THREAD

**Issue by philderbeast** [BlockScope/flare-timing#236]
Flare timing is showing Jonathan Kinred as completing [Forbes 2012, task 6](https://www.forbesflatlands.com/results-show?id_results=11&db=results2012&class=results_open) in a time of `04:43:21` but the official results are showing him as completing the distance of 201.8km but not getting a finishing time, not getting an elapsed time and therefore not getting arrival or time points for this task.

**Comment by philderbeast** [comment]
See also Trent Brown on the last task of this comp coming in `+00:06:42` later if flare-timing is to be believed.

**Comment by philderbeast** [comment]
@jkinred do you remember what happened that day?

**Comment by jkinred** [comment]
It was a line finish and I touched down a couple of steps before the line and technically didn't "make goal".

First comp and I didn't know about downwind crashes, [Gerolf's donkey punch](https://www.youtube.com/watch?v=btSLxxv9oyo) or simply that the line projects beyond the physical marker and I could have landed a few metres to the side!

Planning on replacing FS?

**Comment by philderbeast** [comment]
I'm not yet drawing line goals on the map or scoring to the line but when I do this is going to make a great test case.

I'm not replacing FS anytime soon. That's CIVL's decision anyhow. I have a more modest goal to create a reference implementation of GAP.

**Comment by philderbeast** [comment]
An interesting glitch, showing Jonathan Kinred making goal by hitting what would be a circle but with the interpolated point projected onto the line. Some of the solution is working, other parts not yet.

<img width="353" alt="Screen Shot 2019-04-26 at 2 44 36 PM" src="https://user-images.githubusercontent.com/633283/56829500-e2d7f200-6831-11e9-9c63-70e259811f06.png">

**Comment by philderbeast** [comment]
After the fix showing that Jonathan gets very close to the line but doesn't cross it.

<img width="312" alt="Screen Shot 2019-04-26 at 5 06 44 PM" src="https://user-images.githubusercontent.com/633283/56836588-c1810100-6845-11e9-8b20-3272f43cfc79.png">
